---
- name: Configure PHP
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    mode: 0644
    owner: root
    group: root

- name: Configure PHP Xdebug
  template:
    src: xdebug.ini.j2
    dest: /etc/php.d/xdebug.ini
    mode: 0644
    owner: root
    group: root

- name: Configure PHP-ZTS Xdebug
  template:
    src: xdebug-zts.ini.j2
    dest: /etc/php-zts.d/xdebug.ini
    mode: 0644
    owner: root
    group: root

- name: Change ownership of PHP session and cache folders
  file:
    path: "/var/lib/php/{{ item }}"
    owner: vagrant
    group: vagrant
    mode: 0770
  with_items:
    - session
    - wsdlcache
