---
- name: "Provision Vagrant"
  hosts: default
  become: true
  remote_user: vagrant
  roles:
    - repo_install
    - common
    - rabbitmq
    - java
    - solr
    - mysql
    - redis
    - php7
    - composer
    - bash
    - apache
