---
- name: Add logging configuration
  template:
    src: logging.yml.j2
    dest: /etc/elasticsearch/logging.yml
    mode: 0741
    owner: root
    group: elasticsearch
  notify: Restart Elasticsearch