---
mysql_repo_url: "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"
mysql_user: mysql
mysql_root_password: password
mysql_log_directory: /var/log/mysql
mysql_data_directory: /var/lib/mysql
mysql_port: 3306
mysql_server_id: 1
