---
- name: Install MySQL repo
  yum:
    name: "{{ mysql_repo_url }}"
    state: present

- name: Install MySQL
  yum:
    name: "mysql"
    enablerepo: remi
    state: present

- name: Install MySQL Server
  yum:
    name: "mysql-server"
    enablerepo: remi
    state: present
